# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b7f89b0c6211abcd814cf1b623e8bfb55f66672e8d76c21d374d9cd6211c5bbab8277d87c0c848be078b025bc0beab80d28014353ec6f6ca67dd19381461ded

test:
  secret_key_base: a37e2415056e9264288c0d4351014e3746fb0e0582dbc08394496d8af9c043bf1b286b960716cd22191ecae7fa59cdac85beb4c655f917f1b0f0baffc2ab1952

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
